Numpy Questions

Task 1: Creating Arrays


1. Write a Python program to:
--> Create a 1D NumPy array of 10 integers ranging from 1 to 10.
--> Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.
--> Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
2. Display the shape, size, and datatype of each array

In [2]:
import numpy as np

In [3]:
# 1D Numpy array
ar1=np.arange(1,11)
print(ar1.shape)
print(ar1.size)
print(type(ar1))
ar1

(10,)
10
<class 'numpy.ndarray'>


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#2D Numpy array
ar2=np.arange(1,10).reshape(3,3)
print(ar2.shape)
print(ar2.size)
print(type(ar2))
ar2

(3, 3)
9
<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# 3D numpy array
ar3=np.random.rand(3,5,3)
print(ar3.shape)
print(ar3.size)
print(type(ar3))
ar3

(3, 5, 3)
45
<class 'numpy.ndarray'>


array([[[0.14702548, 0.68122367, 0.94980244],
        [0.5073726 , 0.88806827, 0.73017404],
        [0.41091229, 0.98586645, 0.09048196],
        [0.0476595 , 0.44417315, 0.98299032],
        [0.16479304, 0.85941109, 0.62670781]],

       [[0.30759847, 0.10892307, 0.80522448],
        [0.25847078, 0.43697189, 0.47526174],
        [0.17787393, 0.56762828, 0.34267266],
        [0.23323262, 0.72271566, 0.27913011],
        [0.47879952, 0.42441937, 0.13231868]],

       [[0.93568419, 0.12054396, 0.61694251],
        [0.2742493 , 0.71449255, 0.68110398],
        [0.8310702 , 0.52502891, 0.46334556],
        [0.96348104, 0.11953371, 0.38773988],
        [0.60702853, 0.60491963, 0.60140566]]])

Task 2: Array indexing and slicing


1. Create a NumPy array from the following list:
-->data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
2. Write a Python program to:
-->Retrieve the first three elements of the array.
-->Retrieve every alternate element of the array.
-->Reverse the array.
3. Perform the above operations and display the results

In [6]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
list=np.array(data)
print(list[0:3])
print(list[::2])
print(list[::-1])

[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


Task 3: Mathematical Operations:-


1. Create two NumPy arrays, A and B, each with 5 random integers between 1 and 20.

2. Write a Python program to:-

--> Add, subtract, multiply, and divide the two arrays element-wise.

--> Compute the dot product of the arrays.

--> Find the mean, median, standard deviation, and variance o--> array A.

--> Identify the maximum and minimum values in array B and their indices

In [8]:
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print(B)
add=A+B
sub=A-B
mul=A*B
div=A/B
print("Addition = ",add)
print("Subtraction = ",sub)
print("Multiplication = ",mul)
print("Division = ",div)

[14 14  5  7 12]
[ 2  8 11 17 12]
Addition =  [16 22 16 24 24]
Subtraction =  [ 12   6  -6 -10   0]
Multiplication =  [ 28 112  55 119 144]
Division =  [7.         1.75       0.45454545 0.41176471 1.        ]


In [10]:
# dot product of the arrays.
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A,B)
dot_pro = np.dot(A, B)
# dot_product = A @ B
print(dot_pro)

[ 9 10 13 16  8] [19  6 14  2  9]
517


In [11]:
# calculating mean, median, standard deviation,
#  and variance o--> array A.
A=np.random.randint(1,20,5)
print(A)
print("Mean = ",np.mean(A))
print("Median = ",np.median(A))
print("Standard deviation = ",np.std(A))
print("Varience = ",np.var(A))


[10  3  1 14  2]
Mean =  6.0
Median =  3.0
Standard deviation =  5.0990195135927845
Varience =  26.0


In [12]:
# finding maximum and minimum values in array B 
# and their indices
B=np.random.randint(1,20,5)
print(B)
print("Maximum = ",np.max(B))
print("Minimum = ",np.min(B))
print("Maximum index = ",np.argmax(B))
print("Minimum index = ",np.argmin(B))

[11 16  5 16  7]
Maximum =  16
Minimum =  5
Maximum index =  1
Minimum index =  2


Task 4: Reshaping and Transposing


1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
2. Write a Python program to:

-->Reshape the array into a 2D array of shape (4, 3).

-->Reshape the array into a 3D array of shape (2, 2, 3).

-->Transpose the reshaped 2D array and display its shape.

In [13]:
list=np.random.randint(1,12,12)
print(list)
print("2D Array of Size 4 X 3")
print(list.reshape(4,3))
print("3D Array of Size 2 X 2 X 3  ")
print(list.reshape(2,2,3))
print("Transpose of 2D Array")
print(np.transpose(list.reshape(4,3)))
print("Transpose of 2D Array and its shape")
print(np.transpose(list.reshape(4,3)).shape)

[ 1  5 11  5  1  2 10  5  7  9  2  3]
2D Array of Size 4 X 3
[[ 1  5 11]
 [ 5  1  2]
 [10  5  7]
 [ 9  2  3]]
3D Array of Size 2 X 2 X 3  
[[[ 1  5 11]
  [ 5  1  2]]

 [[10  5  7]
  [ 9  2  3]]]
Transpose of 2D Array
[[ 1  5 10  9]
 [ 5  1  5  2]
 [11  2  7  3]]
Transpose of 2D Array and its shape
(3, 4)


Task 5: Boolean Masking and Filtering:-


1. Create a NumPy array with 15 random integers between 10 and 50.
2. Write a Python program to:

-->Find all elements greater than 25.

-->Replace all elements less than 30 with 0.

-->Count the number of elements divisible by 5.

In [14]:
list=np.random.randint(10,50,15)
print(list)
print("Numbers Greater than 25 :")
print(list[list>25])
print("Replacing all elements less than 30 with 0 :")
list[list<30]=0
print(list)
print("number of nonZero elements divisible by 5 :")
print(np.count_nonzero(list[list%5==0]))
print("number of  elements divisible by 5 :")
print(np.count_nonzero(list%5==0))

[45 20 29 19 14 19 49 15 38 36 25 38 34 31 26]
Numbers Greater than 25 :
[45 29 49 38 36 38 34 31 26]
Replacing all elements less than 30 with 0 :
[45  0  0  0  0  0 49  0 38 36  0 38 34 31  0]
number of nonZero elements divisible by 5 :
1
number of  elements divisible by 5 :
9


Task 6: Working with Built-in Functions:-


1. Use NumPy's built-in functions to:

-->Create an array of 10 equally spaced values between 0 and 1.

-->Create an identity matrix of size 4x4.

-->Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

In [16]:
# Create an array of 10 equally spaced values between 0 and 1.
list=np.linspace(0,1,10)
print(list)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [17]:
# Create an identity matrix of size 4x4.
print(np.eye(4,dtype="int"))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [18]:
# Generate a 1D array of 20 random integers between 1 and 100,
# sorting it, and find the 5 largest elements.

list=np.random.randint(1,100,20)
print("Original Array : ")
print(list)
print("Sorted Array : ")
print(np.sort(list))
print("5 largest elements : ")
print(np.sort(list)[-5:][::-1])

Original Array : 
[39 80 72 70 24 37  9 25 90 15 69 95  6 56 31 89 80 97 12 82]
Sorted Array : 
[ 6  9 12 15 24 25 31 37 39 56 69 70 72 80 80 82 89 90 95 97]
5 largest elements : 
[97 95 90 89 82]


Task 7: Generic:-


1. Create a Python program that:

-->Generates two large random arrays of size (100, 100).

-->Performs matrix multiplication on the two arrays.

-->Finds the determinant and inverse of the resulting matrix (if possible).

-->Measures the time taken to complete these operations.

In [19]:
import time

# two random 100x100 arrays
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# starting the timer
start = time.time()
print(f"Operation Start time :{start} \n")

# multiplying the matrices
C = np.dot(A, B)
print("Matrices multiplied \n")
print(C)

# determinant
det_C = np.linalg.det(C)
print(f"Determinant of the result: {det_C} ")


# calculating inverse if determinant is not zero
if np.isclose(det_C, 0):
    inverse_C = None
    invert = False
else:
    inverse_C = np.linalg.inv(C)
    invert = True

# timer ended
end = time.time()
print(f"Operation end time :{end} ")

elapsed_time = end - start

print("Matrix is invertible." if invert else "Matrix is not invertible.")
if invert:
    print("Inverse matrix calculated successfully.")
    print(inverse_C)
print(f"Time taken: {elapsed_time:.4f} seconds")


Operation Start time :1752350785.2790954 

Matrices multiplied 

[[24.95781535 22.67312686 22.30560781 ... 25.85287136 25.79168631
  25.49284486]
 [28.9713515  26.13097499 23.95743275 ... 26.96274293 28.20406996
  28.31350936]
 [27.16471886 24.46075147 24.57637286 ... 25.00382232 25.18113841
  28.07396943]
 ...
 [25.47712708 24.03357371 21.03690321 ... 23.97195704 25.50436056
  23.58736258]
 [25.65949981 21.5668706  24.26338498 ... 24.61035213 24.42720757
  25.73815721]
 [31.36572816 27.36194492 26.57749939 ... 27.93004642 31.88327633
  31.18186768]]
Determinant of the result: -1.1575551192689852e+51 
Operation end time :1752350785.3429577 
Matrix is invertible.
Inverse matrix calculated successfully.
[[-2.28756162  4.14976474 -4.85160775 ... -6.24985428  2.71035096
  -0.02490012]
 [-0.83661477  4.12599817 -3.49133425 ... -3.54344258  1.06462964
   2.36624712]
 [ 1.06534256 -4.06381986  3.25343592 ...  4.32251494 -1.5316735
  -0.88211814]
 ...
 [-2.90245051  4.86615179 -4.95562802 ... 